import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-white grid grid-cols-1 lg:grid-cols-2">
        {/* LEFT SIDE */}
        <div
          style={{
            background:
              "url('https://images.pexels.com/photos/11719086/pexels-photo-11719086.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')",
          }}
          className="relative p-16 rounded-tr-[5em] rounded-br-[5em]"
        >
          <div className="h-full w-full flex flex-col justify-between p-12 bg-gray-500 bg-opacity-40 rounded-[3em]">
            <p>Logo</p>
            <div>
              Welcome to We're a Digital Agency. We are glad to see you again!
              Get access to your Orders, Wishlist and Recommendations.
            </div>
            <div>
              <p>Don't have an account?</p>
              <a href="/">Register Now</a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
